### ISSUE TITLE
openocd configuration/setup on macOS is wrong.

### ISSUE THREAD

**Issue by duaneellissd** [gnu-mcu-eclipse/gnu-mcu-eclipse.github.io-source#11]
Not sure if this should be here, or elsewhere

On a MAC - (new MacBook Pro, Catalina) current instructions to setup opened do not work

Part 1 -  when I select the OpenOCD xpack.

the result is this:
```
/Users/duane/Library/xPacks/@xpack-dev-tools/openocd/0.10.0-12.1/.content/bin
```
The actual result should be:
```
/Users/duane/Library/xPacks/@gnu-mcu-eclipse/openocd/0.10.0-12.1/.content/bin
```
Part 2 - 
For some reason - under the MacOS - there is *ZERO* means to browse to the  /home/duane/Library location.

This is evidently *COMMON*  - see here:

http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/

It might be helpful - Perhaps you did this already ... but to have a small single web/wiki page that talks about some of the "Mac-isms" that one must deal with.

**Comment by ilg-ul** [comment]
Which page do you refer to?

**Comment by duaneellissd** [comment]
This page:  https://gnu-mcu-eclipse.github.io/debug/openocd/#define-the-openocd-folder-location

Part 1 - When following the instructions, I choose the VERSION NUMBER and "folder" field is auto populated incorrectly as described (wrong xpack name is inserted)

Part 2 - If you attempt to "browse" there are secondary problems

As you attempt to browse to the location:  /Users/<yourname>/Library - the "user-library" directory is not present in the browsable list of directories.

Removing the "Hidden" attribute does not help.

The work around is to figure out the entire path ... and cut/paste the path as text.
(Yuck, that's ugly)

**Comment by duaneellissd** [comment]
Example of browsable problem, no library present
![image](https://user-images.githubusercontent.com/17130161/71485584-a268b380-27c6-11ea-8fbf-2be3f9412dea.png)

**Comment by ilg-ul** [comment]
> and "folder" field is auto populated incorrectly as described (wrong xpack name is inserted)

What does 'wrong' mean? 

If you installed the package properly, it should read something like `/Users/ilg/Library/xPacks/@xpack-dev-tools/openocd/0.10.0-13.1/.content/bin`.

> the "user-library" directory is not present in the browsable list of directories.

Unfortunately Apple decided to hide this folder, but you can make it visible with:

```console
$ /usr/bin/chflags nohidden ~/Library
$ xattr -d com.apple.FinderInfo ~/Library
```

I did not try this on Catalina yet, so if you have a different experience, please let me know and we'll find a solution.

But the automated install method via xpm should not need any manual browsing.

**Comment by ilg-ul** [comment]
I added these two lines to the xpm install page:

https://xpack.github.io/xpm/install/#macos-specifics

**Comment by duaneellissd** [comment]
Thanks - I needed both - line 1 and line 2
Can't solve the "dot" dir problem yet... 

I followed the automatic install method 'exactly', 

This says:  https://xpack.github.io/openocd/install/  `xpm install --global @xpack-dev-tools/openocd@latest`

Verses: https://gnu-mcu-eclipse.github.io/openocd/install/ (which is marked as deprecated)

Which says `@gnu-mcu-eclipse/openocd`. 

Note the difference `@xpack` verses `@gnu-mcu`

But this makes me think here is something else going on.

**Comment by ilg-ul** [comment]
I'm afraid I can't follow you.

What 'dot' problem? If you use the latest plug-ins and the latest openocd xPack, you simply select the version and it automatically identifies the correct location.

Where do you encounter the 'dot' problem?

And yes, openocd was moved from the @gnu-mcu-eclipse scope to @xpack-dev-tools, in preparation of migrating the GNU MCU Eclipse plug-ins to an Eclipse Foundation project.

> Note the difference @xpack verses @gnu-mcu

yes, what is wrong with it?

**Comment by duaneellissd** [comment]
Dot problem = ".content" directory being hidden, and not being able to browse through a dot directory - nothing you can solve, just annoying as hell.  Much like the Windows "hide hidden files" option - the dot problem is the apple equivalent.

* >> what is wrong with it?

* step 1 - Install *ONLY* the GNU version of openocd, do not install both.
* step 2 - Choose the xpack version, your choice is 0.10.0-12.1
* step 3 - the resulting path is `~/Libraries/@xpacks-dev-tools`
But the tool is in the gnu folder.

The Preferences dialog box has a (X) Value must be an existing directory at the top.

* What's wrong is this:  Maybe the problem is now moot ... but if/when a package moves from location (A) to Location (B), for example 'gnumcu' to 'xpacks' the selector tool should probably honor the location the package was found in.

* Or - it should not allow two packages to have the same name in two different '@' directories.

* It seems the xpack selection has some prior knowledge or hidden requirement that package (X) shall only be found in Directory(Y) and not Directory(Z)

* Again, maybe this is moot.

**Comment by ilg-ul** [comment]
> Dot problem = ".content" directory being hidden, and not being able to browse through a dot directory - nothing you can solve, just annoying as hell. Much like the Windows "hide hidden files" option - the dot problem is the apple equivalent.

In this case the culprit is Eclipse, as far as I can tell, Apple or Windows have no problems to browse dot folders. NothingIi can do, at least for now. The solution would be to patch the Eclipse core code, but I'm not sure if I'll be able to do this.

> the resulting path is ~/Libraries/@xpacks-dev-tools But the tool is in the gnu folder.

I don't think so, the tool **is** in Libraries, otherwise the version number should not be available for selection.

if you have older versions installed in other locations, they are ignored if you xPacks.

> The Preferences dialog box has a (X) Value must be an existing directory at the top.

Yes, this is an Eclipse default. It can be turned off with a global configuration.

> but if/when a package moves from location (A) to Location (B), for example 'gnumcu' to 'xpacks' the selector tool should probably honor the location the package was found in.

the package does not move from one location to another. the old versions remain in the old location, and the new releases are installed in the new location.

however, if you manually move folders around, or manually install packages in various locations, it is possible to get to a confusing state.

I suggest you simply delete the Library/xPacks folder, and all obsolete locations, then install via xpm the new releases and everything should work smoothly.

**Comment by duaneellissd** [comment]
WRT - the "dot problem" - I found this to be helpful to somebody who comes across this in a google search.

https://stackoverflow.com/questions/47910444/how-to-display-hidden-files-in-mac

On a Mac:  CMD-SHIFT-DOT - Toggles DOT file visibility, seems to work quite universally.

The other helpful one is: CMD-SHIFT-G, where you can type any path you wish including any ".dot" location

Otherwise I think you can close this ticket off.

Thank you very much for your responsiveness to this.

**Comment by ilg-ul** [comment]
> CMD-SHIFT-DOT

Ah, you were right, it is an Apple thing. I thought it is Eclipse since I saw a similar behaviour with Eclipse on Linux, but I might be wrong.

I added this to the install and FAQ pages

- https://xpack.github.io/xpm/install/
- https://xpack.github.io/xpm/faq/

Thank you for improving the project documentation.
