### ISSUE TITLE
Update pages with tool paths to refer to the MCU group

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/gnu-mcu-eclipse.github.io-source#3]
Replace images with the old tool paths, and update text to refer to the pages below the new MCU group.

**Comment by chapatt** [comment]
I just went to suggest this change and found this issue. Just as a reminder for a couple pages to which this issue applies, here's a question on stackoverflow: https://stackoverflow.com/questions/46267329/qemu-eclipse-plug-in-doesnt-seem-to-be-installing-properly. Thanks for all your work!

**Comment by ilg-ul** [comment]
Fixed on 2018-04-25.

@chapatt, please check if the pages are ok now.

**Comment by chapatt** [comment]
@ilg-ul: Looks good to me.

**Comment by ilg-ul** [comment]
ok, thank you.
