### ISSUE TITLE
Typo in https://gnu-mcu-eclipse.github.io/toolchain/riscv/install/ page

### ISSUE THREAD

**Issue by chipnayak** [gnu-mcu-eclipse/gnu-mcu-eclipse.github.io-source#4]
The The xPack install paragraph sample commad reads:

```console
$ xpm install @gnu-mcu-eclipse/risc-none-gcc --global
```

It should be:

```console
$ xpm install @gnu-mcu-eclipse/riscv-none-gcc --global
```

**Comment by ilg-ul** [comment]
oops!

otherwise, did `xpm` work properly on your system? did you use the **xPack...** button in the window to set the path?

**Comment by chipnayak** [comment]
Worked perfectly. Thank you! Have not checked it though, could xpm be used to install eclipse itself too?
Thank you again for all your help. 

Thanks. 
Best Regards. 
-- Chip (chipnayak@yahoo.com) 

    On Tuesday, January 16, 2018 1:46 AM, Liviu Ionescu <notifications@github.com> wrote:
 

 oops!otherwise, did xpm work properly on your system? did you use the xPack... button in the window to set the path?—

**Comment by ilg-ul** [comment]
> could xpm be used to install eclipse itself too?

good question!

in theory it can install any binaries, but the main target were the command line tools.

it installs multiple versions of the read/only tools in a central folder; when different packages refer to specific versions, get links to them.

Eclipse is a bit different, there can be multiple instances of Eclipse installed in various locations (it is recommended to install one instance for each main project or group of related projects), the instances are writable, and do not really fit the profile of xpm tools.

p.s. please do not use email for posting to this tracker.
